package com.example.util;

public class MailBody {
	private String emailSend;
	private String emailTo;
	private String code;
	private String password;
	private String link;
	private boolean send;

	public MailBody(String emailTo, String code) {
		super();
		this.emailTo = emailTo;
		this.code = code;
	}

	public MailBody(String emailTo, String password, String link) {
		super();
		this.emailTo = emailTo;
		this.link = link;
		this.password = password;
	}

	public MailBody(String emailSend, String emailTo, String link, boolean send) {
		super();
		this.emailSend = emailSend;
		this.emailTo = emailTo;
		this.link = link;
		this.send = send;
	}

	public String forgotPassword() {
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">" + "  <head>"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
				+ "    <meta name=\"x-apple-disable-message-reformatting\" />"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />"
				+ "    <meta name=\"color-scheme\" content=\"light dark\" />"
				+ "    <meta name=\"supported-color-schemes\" content=\"light dark\" />" + "    <title></title>"
				+ "    <style type=\"text/css\" rel=\"stylesheet\" media=\"all\">"
				+ "    /* Base ------------------------------ */" + "    "
				+ "    @import url(\"https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap\");"
				+ "    body {" + "      width: 100% !important;" + "      height: 100%;" + "      margin: 0;"
				+ "      -webkit-text-size-adjust: none;" + "    }" + "    " + "    a {" + "      color: #3869D4;"
				+ "    }" + "    " + "    a img {" + "      border: none;" + "    }" + "    " + "    td {"
				+ "      word-break: break-word;" + "    }" + "    " + "    .preheader {"
				+ "      display: none !important;" + "      visibility: hidden;" + "      mso-hide: all;"
				+ "      font-size: 1px;" + "      line-height: 1px;" + "      max-height: 0;" + "      max-width: 0;"
				+ "      opacity: 0;" + "      overflow: hidden;" + "    }"
				+ "    /* Type ------------------------------ */" + "    " + "    body," + "    td," + "    th {"
				+ "      font-family: \"Nunito Sans\", Helvetica, Arial, sans-serif;" + "    }" + "    " + "    h1 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 22px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    h2 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 16px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    h3 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 14px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    td," + "    th {"
				+ "      font-size: 16px;" + "    }" + "    " + "    p," + "    ul," + "    ol," + "    blockquote {"
				+ "      margin: .4em 0 1.1875em;" + "      font-size: 16px;" + "      line-height: 1.625;" + "    }"
				+ "    " + "    p.sub {" + "      font-size: 13px;" + "    }"
				+ "    /* Utilities ------------------------------ */" + "    " + "    .align-right {"
				+ "      text-align: right;" + "    }" + "    " + "    .align-left {" + "      text-align: left;"
				+ "    }" + "    " + "    .align-center {" + "      text-align: center;" + "    }" + "    "
				+ "    .u-margin-bottom-none {" + "      margin-bottom: 0;" + "    }"
				+ "    /* Buttons ------------------------------ */" + "    " + "    .button {"
				+ "      background-color: #3869D4;" + "      border-top: 10px solid #3869D4;"
				+ "      border-right: 18px solid #3869D4;" + "      border-bottom: 10px solid #3869D4;"
				+ "      border-left: 18px solid #3869D4;" + "      display: inline-block;" + "      color: #FFF;"
				+ "      text-decoration: none;" + "      border-radius: 3px;"
				+ "      box-shadow: 0 2px 3px rgba(0, 0, 0, 0.16);" + "      -webkit-text-size-adjust: none;"
				+ "      box-sizing: border-box;" + "    }" + "    " + "    .button--green {"
				+ "      background-color: #22BC66;" + "      border-top: 10px solid #22BC66;"
				+ "      border-right: 18px solid #22BC66;" + "      border-bottom: 10px solid #22BC66;"
				+ "      border-left: 18px solid #22BC66;" + "    }" + "    " + "    .button--red {"
				+ "      background-color: #FF6136;" + "      border-top: 10px solid #FF6136;"
				+ "      border-right: 18px solid #FF6136;" + "      border-bottom: 10px solid #FF6136;"
				+ "      border-left: 18px solid #FF6136;" + "    }" + "    "
				+ "    @media only screen and (max-width: 500px) {" + "      .button {"
				+ "        width: 100% !important;" + "        text-align: center !important;" + "      }" + "    }"
				+ "    /* Attribute list ------------------------------ */" + "    " + "    .attributes {"
				+ "      margin: 0 0 21px;" + "    }" + "    " + "    .attributes_content {"
				+ "      background-color: #F4F4F7;" + "      padding: 16px;" + "    }" + "    "
				+ "    .attributes_item {" + "      padding: 0;" + "    }"
				+ "    /* Related Items ------------------------------ */" + "    " + "    .related {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 25px 0 0 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "    }" + "    " + "    .related_item {"
				+ "      padding: 10px 0;" + "      color: #CBCCCF;" + "      font-size: 15px;"
				+ "      line-height: 18px;" + "    }" + "    " + "    .related_item-title {" + "      display: block;"
				+ "      margin: .5em 0 0;" + "    }" + "    " + "    .related_item-thumb {" + "      display: block;"
				+ "      padding-bottom: 10px;" + "    }" + "    " + "    .related_heading {"
				+ "      border-top: 1px solid #CBCCCF;" + "      text-align: center;" + "      padding: 25px 0 10px;"
				+ "    }" + "    /* Discount Code ------------------------------ */" + "    " + "    .discount {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 24px;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;"
				+ "      background-color: #F4F4F7;" + "      border: 2px dashed #CBCCCF;" + "    }" + "    "
				+ "    .discount_heading {" + "      text-align: center;" + "    }" + "    " + "    .discount_body {"
				+ "      text-align: center;" + "      font-size: 15px;" + "    }"
				+ "    /* Social Icons ------------------------------ */" + "    " + "    .social {"
				+ "      width: auto;" + "    }" + "    " + "    .social td {" + "      padding: 0;"
				+ "      width: auto;" + "    }" + "    " + "    .social_icon {" + "      height: 20px;"
				+ "      margin: 0 8px 10px 8px;" + "      padding: 0;" + "    }"
				+ "    /* Data table ------------------------------ */" + "    " + "    .purchase {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 35px 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }" + "    "
				+ "    .purchase_content {" + "      width: 100%;" + "      margin: 0;" + "      padding: 25px 0 0 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "    }" + "    " + "    .purchase_item {"
				+ "      padding: 10px 0;" + "      color: #51545E;" + "      font-size: 15px;"
				+ "      line-height: 18px;" + "    }" + "    " + "    .purchase_heading {"
				+ "      padding-bottom: 8px;" + "      border-bottom: 1px solid #EAEAEC;" + "    }" + "    "
				+ "    .purchase_heading p {" + "      margin: 0;" + "      color: #85878E;" + "      font-size: 12px;"
				+ "    }" + "    " + "    .purchase_footer {" + "      padding-top: 15px;"
				+ "      border-top: 1px solid #EAEAEC;" + "    }" + "    " + "    .purchase_total {"
				+ "      margin: 0;" + "      text-align: right;" + "      font-weight: bold;" + "      color: #333333;"
				+ "    }" + "    " + "    .purchase_total--label {" + "      padding: 0 15px 0 0;" + "    }" + "    "
				+ "    body {" + "      background-color: #F2F4F6;" + "      color: #51545E;" + "    }" + "    "
				+ "    p {" + "      color: #51545E;" + "    }" + "    " + "    .email-wrapper {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;"
				+ "      background-color: #F2F4F6;" + "    }" + "    " + "    .email-content {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }"
				+ "    /* Masthead ----------------------- */" + "    " + "    .email-masthead {"
				+ "      padding: 25px 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .email-masthead_logo {" + "      width: 94px;" + "    }" + "    " + "    .email-masthead_name {"
				+ "      font-size: 16px;" + "      font-weight: bold;" + "      color: #A8AAAF;"
				+ "      text-decoration: none;" + "      text-shadow: 0 1px 0 white;" + "    }"
				+ "    /* Body ------------------------------ */" + "    " + "    .email-body {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }" + "    "
				+ "    .email-body_inner {" + "      width: 570px;" + "      margin: 0 auto;" + "      padding: 0;"
				+ "      -premailer-width: 570px;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      background-color: #FFFFFF;" + "    }" + "    "
				+ "    .email-footer {" + "      width: 570px;" + "      margin: 0 auto;" + "      padding: 0;"
				+ "      -premailer-width: 570px;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .email-footer p {" + "      color: #A8AAAF;" + "    }" + "    " + "    .body-action {"
				+ "      width: 100%;" + "      margin: 30px auto;" + "      padding: 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .body-sub {" + "      margin-top: 25px;" + "      padding-top: 25px;"
				+ "      border-top: 1px solid #EAEAEC;" + "    }" + "    " + "    .content-cell {"
				+ "      padding: 45px;" + "    }" + "    /*Media Queries ------------------------------ */" + "    "
				+ "    @media only screen and (max-width: 600px) {" + "      .email-body_inner,"
				+ "      .email-footer {" + "        width: 100% !important;" + "      }" + "    }" + "    "
				+ "    @media (prefers-color-scheme: dark) {" + "      body," + "      .email-body,"
				+ "      .email-body_inner," + "      .email-content," + "      .email-wrapper,"
				+ "      .email-masthead," + "      .email-footer {" + "        background-color: #333333 !important;"
				+ "        color: #FFF !important;" + "      }" + "      p," + "      ul," + "      ol,"
				+ "      blockquote," + "      h1," + "      h2," + "      h3," + "      span,"
				+ "      .purchase_item {" + "        color: #FFF !important;" + "      }"
				+ "      .attributes_content," + "      .discount {" + "        background-color: #222 !important;"
				+ "      }" + "      .email-masthead_name {" + "        text-shadow: none !important;" + "      }"
				+ "    }" + "    " + "    :root {" + "      color-scheme: light dark;"
				+ "      supported-color-schemes: light dark;" + "    }" + "    </style>" + "    <!--[if mso]>"
				+ "    <style type=\"text/css\">" + "      .f-fallback  {" + "        font-family: Arial, sans-serif;"
				+ "      }" + "    </style>" + "  <![endif]-->" + "  </head>" + "  <body>"
				+ "    <span class=\"preheader\">Use this code to reset password, please do not share this code with anyone, it is only valid for 15 minutes..</span>"
				+ "    <table class=\"email-wrapper\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "      <tr>" + "        <td align=\"center\">"
				+ "          <table class=\"email-content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "            <tr>" + "              <td class=\"email-masthead\">"
				+ "                <a href=\"#\" class=\"f-fallback email-masthead_name\">"
				+ "                ONLINE SHOP" + "              </a>" + "              </td>" + "            </tr>"
				+ "            <!-- Email Body -->" + "            <tr>"
				+ "              <td class=\"email-body\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\">"
				+ "                <table class=\"email-body_inner\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "                  <!-- Body content -->" + "                  <tr>"
				+ "                    <td class=\"content-cell\">" + "                      <div class=\"f-fallback\">"
				+ "                        <h1>************ Hi " + emailTo + " ************</h1>"
				+ "                        <p>You have recently requested a password reset for your online shop account.Use below code to reset.<strong>This password reset is only valid for the next 15 minutes.</strong></p>"
				+ "                        <table class=\"body-sub\" role=\"presentation\">"
				+ "                          <tr>" + "                            <td>"
				+ "                              <p class=\"f-fallback sub\">Your password reset code :<h1>" + code
				+ "</h1></p>" + "                            </td>" + "                          </tr>"
				+ "                        </table>" + "                      </div>" + "                    </td>"
				+ "                  </tr>" + "                </table>" + "              </td>" + "            </tr>"
				+ "            <tr>" + "              <td>"
				+ "                <table class=\"email-footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "                  <tr>" + "                    <td class=\"content-cell\" align=\"center\">"
				+ "                      <p class=\"f-fallback sub align-center\">"
				+ "                        [Company Name, LLC]" + "                        <br>1234 Street Rd."
				+ "                        <br>Suite 1234" + "                      </p>" + "                    </td>"
				+ "                  </tr>" + "                </table>" + "              </td>" + "            </tr>"
				+ "          </table>" + "        </td>" + "      </tr>" + "    </table>" + "  </body>" + "</html>";
	}

	public String register() {
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">" + "  <head>"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
				+ "    <meta name=\"x-apple-disable-message-reformatting\" />"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />"
				+ "    <meta name=\"color-scheme\" content=\"light dark\" />"
				+ "    <meta name=\"supported-color-schemes\" content=\"light dark\" />" + "    <title></title>"
				+ "    <style type=\"text/css\" rel=\"stylesheet\" media=\"all\">"
				+ "    /* Base ------------------------------ */" + "    "
				+ "    @import url(\"https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap\");"
				+ "    body {" + "      width: 100% !important;" + "      height: 100%;" + "      margin: 0;"
				+ "      -webkit-text-size-adjust: none;" + "    }" + "    " + "    a {" + "      color: #3869D4;"
				+ "    }" + "    " + "    a img {" + "      border: none;" + "    }" + "    " + "    td {"
				+ "      word-break: break-word;" + "    }" + "    " + "    .preheader {"
				+ "      display: none !important;" + "      visibility: hidden;" + "      mso-hide: all;"
				+ "      font-size: 1px;" + "      line-height: 1px;" + "      max-height: 0;" + "      max-width: 0;"
				+ "      opacity: 0;" + "      overflow: hidden;" + "    }"
				+ "    /* Type ------------------------------ */" + "    " + "    body," + "    td," + "    th {"
				+ "      font-family: \"Nunito Sans\", Helvetica, Arial, sans-serif;" + "    }" + "    " + "    h1 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 22px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    h2 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 16px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    h3 {"
				+ "      margin-top: 0;" + "      color: #333333;" + "      font-size: 14px;"
				+ "      font-weight: bold;" + "      text-align: left;" + "    }" + "    " + "    td," + "    th {"
				+ "      font-size: 16px;" + "    }" + "    " + "    p," + "    ul," + "    ol," + "    blockquote {"
				+ "      margin: .4em 0 1.1875em;" + "      font-size: 16px;" + "      line-height: 1.625;" + "    }"
				+ "    " + "    p.sub {" + "      font-size: 13px;" + "    }"
				+ "    /* Utilities ------------------------------ */" + "    " + "    .align-right {"
				+ "      text-align: right;" + "    }" + "    " + "    .align-left {" + "      text-align: left;"
				+ "    }" + "    " + "    .align-center {" + "      text-align: center;" + "    }" + "    "
				+ "    .u-margin-bottom-none {" + "      margin-bottom: 0;" + "    }"
				+ "    /* Buttons ------------------------------ */" + "    " + "    .button {"
				+ "      background-color: #3869D4;" + "      border-top: 10px solid #3869D4;"
				+ "      border-right: 18px solid #3869D4;" + "      border-bottom: 10px solid #3869D4;"
				+ "      border-left: 18px solid #3869D4;" + "      display: inline-block;" + "      color: #FFF;"
				+ "      text-decoration: none;" + "      border-radius: 3px;"
				+ "      box-shadow: 0 2px 3px rgba(0, 0, 0, 0.16);" + "      -webkit-text-size-adjust: none;"
				+ "      box-sizing: border-box;" + "    }" + "    " + "    .button--green {"
				+ "      background-color: #22BC66;" + "      border-top: 10px solid #22BC66;"
				+ "      border-right: 18px solid #22BC66;" + "      border-bottom: 10px solid #22BC66;"
				+ "      border-left: 18px solid #22BC66;" + "    }" + "    " + "    .button--red {"
				+ "      background-color: #FF6136;" + "      border-top: 10px solid #FF6136;"
				+ "      border-right: 18px solid #FF6136;" + "      border-bottom: 10px solid #FF6136;"
				+ "      border-left: 18px solid #FF6136;" + "    }" + "    "
				+ "    @media only screen and (max-width: 500px) {" + "      .button {"
				+ "        width: 100% !important;" + "        text-align: center !important;" + "      }" + "    }"
				+ "    /* Attribute list ------------------------------ */" + "    " + "    .attributes {"
				+ "      margin: 0 0 21px;" + "    }" + "    " + "    .attributes_content {"
				+ "      background-color: #F4F4F7;" + "      padding: 16px;" + "    }" + "    "
				+ "    .attributes_item {" + "      padding: 0;" + "    }"
				+ "    /* Related Items ------------------------------ */" + "    " + "    .related {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 25px 0 0 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "    }" + "    " + "    .related_item {"
				+ "      padding: 10px 0;" + "      color: #CBCCCF;" + "      font-size: 15px;"
				+ "      line-height: 18px;" + "    }" + "    " + "    .related_item-title {" + "      display: block;"
				+ "      margin: .5em 0 0;" + "    }" + "    " + "    .related_item-thumb {" + "      display: block;"
				+ "      padding-bottom: 10px;" + "    }" + "    " + "    .related_heading {"
				+ "      border-top: 1px solid #CBCCCF;" + "      text-align: center;" + "      padding: 25px 0 10px;"
				+ "    }" + "    /* Discount Code ------------------------------ */" + "    " + "    .discount {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 24px;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;"
				+ "      background-color: #F4F4F7;" + "      border: 2px dashed #CBCCCF;" + "    }" + "    "
				+ "    .discount_heading {" + "      text-align: center;" + "    }" + "    " + "    .discount_body {"
				+ "      text-align: center;" + "      font-size: 15px;" + "    }"
				+ "    /* Social Icons ------------------------------ */" + "    " + "    .social {"
				+ "      width: auto;" + "    }" + "    " + "    .social td {" + "      padding: 0;"
				+ "      width: auto;" + "    }" + "    " + "    .social_icon {" + "      height: 20px;"
				+ "      margin: 0 8px 10px 8px;" + "      padding: 0;" + "    }"
				+ "    /* Data table ------------------------------ */" + "    " + "    .purchase {"
				+ "      width: 100%;" + "      margin: 0;" + "      padding: 35px 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }" + "    "
				+ "    .purchase_content {" + "      width: 100%;" + "      margin: 0;" + "      padding: 25px 0 0 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "    }" + "    " + "    .purchase_item {"
				+ "      padding: 10px 0;" + "      color: #51545E;" + "      font-size: 15px;"
				+ "      line-height: 18px;" + "    }" + "    " + "    .purchase_heading {"
				+ "      padding-bottom: 8px;" + "      border-bottom: 1px solid #EAEAEC;" + "    }" + "    "
				+ "    .purchase_heading p {" + "      margin: 0;" + "      color: #85878E;" + "      font-size: 12px;"
				+ "    }" + "    " + "    .purchase_footer {" + "      padding-top: 15px;"
				+ "      border-top: 1px solid #EAEAEC;" + "    }" + "    " + "    .purchase_total {"
				+ "      margin: 0;" + "      text-align: right;" + "      font-weight: bold;" + "      color: #333333;"
				+ "    }" + "    " + "    .purchase_total--label {" + "      padding: 0 15px 0 0;" + "    }" + "    "
				+ "    body {" + "      background-color: #F2F4F6;" + "      color: #51545E;" + "    }" + "    "
				+ "    p {" + "      color: #51545E;" + "    }" + "    " + "    .email-wrapper {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;"
				+ "      background-color: #F2F4F6;" + "    }" + "    " + "    .email-content {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }"
				+ "    /* Masthead ----------------------- */" + "    " + "    .email-masthead {"
				+ "      padding: 25px 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .email-masthead_logo {" + "      width: 94px;" + "    }" + "    " + "    .email-masthead_name {"
				+ "      font-size: 16px;" + "      font-weight: bold;" + "      color: #A8AAAF;"
				+ "      text-decoration: none;" + "      text-shadow: 0 1px 0 white;" + "    }"
				+ "    /* Body ------------------------------ */" + "    " + "    .email-body {" + "      width: 100%;"
				+ "      margin: 0;" + "      padding: 0;" + "      -premailer-width: 100%;"
				+ "      -premailer-cellpadding: 0;" + "      -premailer-cellspacing: 0;" + "    }" + "    "
				+ "    .email-body_inner {" + "      width: 570px;" + "      margin: 0 auto;" + "      padding: 0;"
				+ "      -premailer-width: 570px;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      background-color: #FFFFFF;" + "    }" + "    "
				+ "    .email-footer {" + "      width: 570px;" + "      margin: 0 auto;" + "      padding: 0;"
				+ "      -premailer-width: 570px;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .email-footer p {" + "      color: #A8AAAF;" + "    }" + "    " + "    .body-action {"
				+ "      width: 100%;" + "      margin: 30px auto;" + "      padding: 0;"
				+ "      -premailer-width: 100%;" + "      -premailer-cellpadding: 0;"
				+ "      -premailer-cellspacing: 0;" + "      text-align: center;" + "    }" + "    "
				+ "    .body-sub {" + "      margin-top: 25px;" + "      padding-top: 25px;"
				+ "      border-top: 1px solid #EAEAEC;" + "    }" + "    " + "    .content-cell {"
				+ "      padding: 45px;" + "    }" + "    /*Media Queries ------------------------------ */" + "    "
				+ "    @media only screen and (max-width: 600px) {" + "      .email-body_inner,"
				+ "      .email-footer {" + "        width: 100% !important;" + "      }" + "    }" + "    "
				+ "    @media (prefers-color-scheme: dark) {" + "      body," + "      .email-body,"
				+ "      .email-body_inner," + "      .email-content," + "      .email-wrapper,"
				+ "      .email-masthead," + "      .email-footer {" + "        background-color: #333333 !important;"
				+ "        color: #FFF !important;" + "      }" + "      p," + "      ul," + "      ol,"
				+ "      blockquote," + "      h1," + "      h2," + "      h3," + "      span,"
				+ "      .purchase_item {" + "        color: #FFF !important;" + "      }"
				+ "      .attributes_content," + "      .discount {" + "        background-color: #222 !important;"
				+ "      }" + "      .email-masthead_name {" + "        text-shadow: none !important;" + "      }"
				+ "    }" + "    " + "    :root {" + "      color-scheme: light dark;"
				+ "      supported-color-schemes: light dark;" + "    }" + "    </style>" + "    <!--[if mso]>"
				+ "    <style type=\"text/css\">" + "      .f-fallback  {" + "        font-family: Arial, sans-serif;"
				+ "      }" + "    </style>" + "  <![endif]-->" + "  </head>" + "  <body>"
				+ "    <span class=\"preheader\">Use this code to reset password, please do not share this code with anyone, it is only valid for 15 minutes..</span>"
				+ "    <table class=\"email-wrapper\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "      <tr>" + "        <td align=\"center\">"
				+ "          <table class=\"email-content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "            <tr>" + "              <td class=\"email-masthead\">"
				+ "                <a href=\"#\" class=\"f-fallback email-masthead_name\">"
				+ "                ONLINE SHOP" + "              </a>" + "              </td>" + "            </tr>"
				+ "            <!-- Email Body -->" + "            <tr>"
				+ "              <td class=\"email-body\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\">"
				+ "                <table class=\"email-body_inner\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "                  <!-- Body content -->" + "                  <tr>"
				+ "                    <td class=\"content-cell\">" + "                      <div class=\"f-fallback\">"
				+ "                        <h1>************ Hi " + emailTo + " ************</h1>"
				+ "                        <p>Thank you for trusting shoponline, below is your login password, please visit "
				+ link + "<strong>to login.</strong></p>"
				+ "                        <table class=\"body-sub\" role=\"presentation\">"
				+ "                          <tr>" + "                            <td>"
				+ "                              <p class=\"f-fallback sub\">Your password :<h1>" + password
				+ "</h1></p>" + "                            </td>" + "                          </tr>"
				+ "                        </table>" + "                      </div>" + "                    </td>"
				+ "                  </tr>" + "                </table>" + "              </td>" + "            </tr>"
				+ "            <tr>" + "              <td>"
				+ "                <table class=\"email-footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">"
				+ "                  <tr>" + "                    <td class=\"content-cell\" align=\"center\">"
				+ "                      <p class=\"f-fallback sub align-center\">"
				+ "                        [Company Name, LLC]" + "                        <br>1234 Street Rd."
				+ "                        <br>Suite 1234" + "                      </p>" + "                    </td>"
				+ "                  </tr>" + "                </table>" + "              </td>" + "            </tr>"
				+ "          </table>" + "        </td>" + "      </tr>" + "    </table>" + "  </body>" + "</html>";
	}

	public String shareVideo() {
		return "<!DOCTYPE html>\r\n" + "\r\n"
				+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n"
				+ "<head>\r\n" + "<title></title>\r\n"
				+ "<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\r\n"
				+ "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n"
				+ "<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
				+ "<!--[if !mso]><!-->\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Varela+Round\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Droid+Serif\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Oxygen\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Abril+Fatface\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Cabin\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Permanent+Marker\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<!--<![endif]-->\r\n" + "<style>\r\n" + "		* {\r\n" + "			box-sizing: border-box;\r\n"
				+ "		}\r\n" + "\r\n" + "		body {\r\n" + "			margin: 0;\r\n" + "			padding: 0;\r\n"
				+ "		}\r\n" + "\r\n" + "		a[x-apple-data-detectors] {\r\n"
				+ "			color: inherit !important;\r\n" + "			text-decoration: inherit !important;\r\n"
				+ "		}\r\n" + "\r\n" + "		#MessageViewBody a {\r\n" + "			color: inherit;\r\n"
				+ "			text-decoration: none;\r\n" + "		}\r\n" + "\r\n" + "		p {\r\n"
				+ "			line-height: inherit\r\n" + "		}\r\n" + "\r\n" + "		.desktop_hide,\r\n"
				+ "		.desktop_hide table {\r\n" + "			mso-hide: all;\r\n" + "			display: none;\r\n"
				+ "			max-height: 0px;\r\n" + "			overflow: hidden;\r\n" + "		}\r\n" + "\r\n"
				+ "		@media (max-width:660px) {\r\n" + "\r\n" + "			.desktop_hide table.icons-inner,\r\n"
				+ "			.social_block.desktop_hide .social-table {\r\n"
				+ "				display: inline-block !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.icons-inner {\r\n" + "				text-align: center;\r\n" + "			}\r\n" + "\r\n"
				+ "			.icons-inner td {\r\n" + "				margin: 0 auto;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-content {\r\n" + "				width: 100% !important;\r\n" + "			}\r\n"
				+ "\r\n" + "			.mobile_hide {\r\n" + "				display: none;\r\n" + "			}\r\n"
				+ "\r\n" + "			.stack .column {\r\n" + "				width: 100%;\r\n"
				+ "				display: block;\r\n" + "			}\r\n" + "\r\n" + "			.mobile_hide {\r\n"
				+ "				min-height: 0;\r\n" + "				max-height: 0;\r\n"
				+ "				max-width: 0;\r\n" + "				overflow: hidden;\r\n"
				+ "				font-size: 0px;\r\n" + "			}\r\n" + "\r\n" + "			.desktop_hide,\r\n"
				+ "			.desktop_hide table {\r\n" + "				display: table !important;\r\n"
				+ "				max-height: none !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-1 .column-1 .block-6.paragraph_block td.pad>div {\r\n"
				+ "				font-size: 15px !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-1 .column-1 .block-4.heading_block h1 {\r\n"
				+ "				font-size: 20px !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-1 .column-1 .block-2.heading_block h1 {\r\n"
				+ "				font-size: 22px !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-2 .column-1 .block-2.heading_block h1 {\r\n"
				+ "				font-size: 21px !important;\r\n" + "			}\r\n" + "\r\n"
				+ "			.row-1 .column-1 .block-7.heading_block h2 {\r\n"
				+ "				font-size: 33px !important;\r\n" + "			}\r\n" + "		}\r\n"
				+ "	</style>\r\n" + "</head>\r\n"
				+ "<body style=\"margin: 0; background-color: #ffffff; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n" + "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n" + "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 640px;\" width=\"640\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: top; padding-top: 20px; padding-bottom: 30px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\" style=\"text-align:center;width:100%;padding-top:50px;\">\r\n"
				+ "<h1 style=\"margin: 0; color: #000000; direction: ltr; font-family: 'Permanent Marker', Impact, Charcoal, sans-serif; font-size: 45px; font-weight: 400; letter-spacing: 1px; line-height: 150%; text-align: center; margin-top: 0; margin-bottom: 0;\"><span class=\"tinyMce-placeholder\">Online Shop</span></h1>\r\n"
				+ "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\" style=\"text-align:center;width:100%;padding-top:25px;\">\r\n"
				+ "<h1 style=\"margin: 0; color: #000000; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 15px; font-weight: 400; letter-spacing: 5px; line-height: 150%; text-align: center; margin-top: 0; margin-bottom: 0;\">It's not just about shopping, it's about experiencing</h1>\r\n"
				+ "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-6\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:35px;\">\r\n"
				+ "<div style=\"color:#000000;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;font-weight:400;letter-spacing:0px;line-height:150%;text-align:center;mso-line-height-alt:22.5px;\">\r\n"
				+ "<p style=\"margin: 0;\">Discover our incredible Black Friday sales with huge savings, discount, deals and exclusive offers available for a limited time online and in-stores.</p>\r\n"
				+ "</div>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-7\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\" style=\"padding-top:10px;text-align:center;width:100%;\">\r\n"
				+ "<h2 style=\"margin: 0; color: #000000; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 25px; font-weight: 400; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0;\"><strong><span class=\"tinyMce-placeholder\">UP TO <span style=\"color: #f81313;\">50 % OFF</span></span></strong></h2>\r\n"
				+ "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"button_block block-9\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\" style=\"text-align:center;padding-top:25px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\">\r\n"
				+ "<!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"http://www.example.com/\" style=\"height:48px;width:175px;v-text-anchor:middle;\" arcsize=\"0%\" strokeweight=\"0.75pt\" strokecolor=\"#C1CEDC\" fillcolor=\"#000000\"><w:anchorlock/><v:textbox inset=\"0px,0px,0px,0px\"><center style=\"color:#ffffff; font-family:Tahoma, sans-serif; font-size:18px\"><![endif]--><a href=\""
				+ link
				+ "/\" style=\"text-decoration:none;display:inline-block;color:#ffffff;background-color:#000000;border-radius:0px;width:auto;border-top:1px solid #C1CEDC;font-weight:400;border-right:1px solid #C1CEDC;border-bottom:1px solid #C1CEDC;border-left:1px solid #C1CEDC;padding-top:5px;padding-bottom:5px;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:18px;text-align:center;mso-border-alt:none;word-break:keep-all;\" target=\"_blank\"><span style=\"padding-left:20px;padding-right:20px;font-size:18px;display:inline-block;letter-spacing:3px;\"><span dir=\"ltr\" style=\"word-break: break-word; line-height: 36px;\">SHOP NOW</span></span></a>\r\n"
				+ "<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\r\n" + "</div>\r\n" + "</td>\r\n"
				+ "</tr>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n"
				+ "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n" + "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 640px;\" width=\"640\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 20px; padding-right: 20px; vertical-align: top; padding-top: 20px; padding-bottom: 15px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\" style=\"text-align:center;width:100%;padding-top:25px;\">\r\n"
				+ "<h1 style=\"margin: 0; color: #000000; direction: ltr; font-family: Georgia, Times, 'Times New Roman', serif; font-size: 30px; font-weight: 400; letter-spacing: 1px; line-height: 150%; text-align: center; margin-top: 0; margin-bottom: 0;\"><em><span class=\"tinyMce-placeholder\">Hello "
				+ emailTo + "</span></em></h1>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:35px;padding-left:20px;padding-right:20px;padding-top:10px;\">\r\n"
				+ "<div style=\"color:#000000;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;font-weight:400;letter-spacing:0px;line-height:150%;text-align:center;mso-line-height-alt:22.5px;\">\r\n"
				+ "<p style=\"margin: 0;\"> A friend of yours " + emailSend
				+ " shared our store's product with you. Thank you for your interest in our store.Select shop now to view product details</p>\r\n"
				+ "</div>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n"
				+ "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n" + "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #000000; width: 640px;\" width=\"640\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 50px; padding-bottom: 25px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;width:100%;padding-right:0px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><a href=\"http://www.example.com/\" style=\"outline:none\" tabindex=\"-1\" target=\"_blank\"><img alt=\"Your-Logo\" src=\"images/logo.png\" style=\"display: block; height: auto; border: 0; width: 128px; max-width: 100%;\" title=\"Your-Logo\" width=\"128\"/></a></div>\r\n"
				+ "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" class=\"social_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"pad\">\r\n" + "<div align=\"center\" class=\"alignment\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"social-table\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\" width=\"312px\">\r\n"
				+ "</table>\r\n" + "</div>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
				+ "<div style=\"font-family: sans-serif\">\r\n"
				+ "<div class=\"\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #a5a5a5; line-height: 1.2; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;\">\r\n"
				+ "<p style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\">Company Name © - 2022 All rights reserved</p>\r\n"
				+ "</div>\r\n" + "</div>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n"
				+ "</tbody>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n" + "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 640px;\" width=\"640\">\r\n"
				+ "<tbody>\r\n" + "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"icons_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\r\n"
				+ "<table cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n" + "<td class=\"alignment\" style=\"vertical-align: middle; text-align: center;\">\r\n"
				+ "<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
				+ "<!--[if !vml]><!-->\r\n"
				+ "<table cellpadding=\"0\" cellspacing=\"0\" class=\"icons-inner\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\r\n"
				+ "<!--<![endif]-->\r\n" + "<tr>\r\n"
				+ "<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"https://www.designedwithbee.com/\" style=\"text-decoration: none;\" target=\"_blank\"><img align=\"center\" alt=\"Designed with BEE\" class=\"icon\" height=\"32\" src=\"images/bee.png\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\" width=\"34\"/></a></td>\r\n"
				+ "<td style=\"font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 15px; color: #9d9d9d; vertical-align: middle; letter-spacing: undefined; text-align: center;\"><a href=\"https://www.designedwithbee.com/\" style=\"color: #9d9d9d; text-decoration: none;\" target=\"_blank\">Designed with BEE</a></td>\r\n"
				+ "</tr>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n"
				+ "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n" + "</td>\r\n"
				+ "</tr>\r\n" + "</tbody>\r\n" + "</table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "</tbody>\r\n"
				+ "</table><!-- End -->\r\n" + "</body>\r\n" + "</html>";
	}

}
